# Generated by Django 4.2.16 on 2026-03-14 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.CharField(blank=True, choices=[('prepaid', 'Prepaid meter'), ('municipal', 'Municipal billing'), ('none', 'No electricity')], default='prepaid', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('room', 'Room'), ('cottage', 'Cottage'), ('studio', 'Studio'), ('townhouse', 'Townhouse')], default='house', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_supply',
            field=models.CharField(blank=True, choices=[('constant', 'Constant supply'), ('intermittent', 'Intermittent supply'), ('borehole', 'Borehole'), ('none', 'No water')], default='constant', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ViewingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateField()),
                ('proposed_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('landlord_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests', to='api.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viewing Request',
                'verbose_name_plural': 'Viewing Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
