# Generated by Django 4.2.16 on 2026-03-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_landlordverification_rentalapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.property'),
        ),
    ]
