# Generated by Django 4.2.16 on 2026-03-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_contactmessage_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
