# Generated by Django 4.2.16 on 2026-06-08 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_bio_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='favoriteproperty',
            index=models.Index(fields=['user'], name='favorite_user_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='message_receiver_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_support'], name='message_support_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord'], name='property_landlord_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['district'], name='property_district_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_approved'], name='property_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_approved', 'status'], name='property_approved_status_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='property_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rental_amount'], name='property_rent_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['applicant'], name='application_applicant_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalapplication',
            index=models.Index(fields=['status'], name='application_status_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['tenant'], name='viewing_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingrequest',
            index=models.Index(fields=['property'], name='viewing_property_idx'),
        ),
    ]
